# Metadata about this component, to be used in the CMS
spec:
  structures:
    - blocks
  label: "Breadcrumbs"
  description: Display the path to the current page
  icon: breakfast_dining
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    final_crumb:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  final_crumb:
    comment: If not set, the page title will be used. (This will be trimmed if the title contains special characters.)
