# Metadata about this component, to be used in the CMS
spec:
  structures:
    - blocks
  label: "Cards"
  description: "A grid of information with icons"
  icon: grid_on
  tags: ['content']

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    cards:
      - image:
        icon:
          active: true
          icon_path: outline/language
          icon_color: teal
        title:
        link:
        description:
  styles:
    desktop:
      margin:
        top: 0
        bottom: 0
    tablet:
      margin:
        active: false
        top: 0
        bottom: 0
    mobile:
      margin:
        active: false
        top: 0
        bottom: 0
    background:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  active:
    comment: These values won't be used unless active is enabled.
  desktop:
    comments: Styles for Desktop, unless overridden will also be used for tablet and mobile.
  tablet:
    comments: Styles for Tablet, unless overridden will also be used for mobile.
  mobile:
    comments: Styles for mobile.
  background:
    type: select
    comment: The background color for the entire section
    options:
      values:
        - white
        - caramel
        - sky
        - sea
        - cloudinary-blue
        - cloudinary-blue-light
        - cloudinary-dark-blue
        - ash
        - night
        - transparent
        - rich-black
_structures:
  rows:
    values: 
      - image:
        title:
        description:
