# Metadata about this component, to be used in the CMS
spec:
  structures:
    - blocks
  label: "Tier Cards"
  description: "A grid showing progression of tiers"
  icon: stars
  tags: ["content"]

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    cards:
      - title:
        subtitle:
        border_color:
        benefits:
          - text:
            tooltip:
            bold: false
  styles:
    desktop:
      margin:
        top: 0
        bottom: 0
    tablet:
      margin:
        active: false
        top: 0
        bottom: 0
    mobile:
      margin:
        active: false
        top: 0
        bottom: 0

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  active:
    comment: These values won't be used unless active is enabled.
  desktop:
    comments: Styles for Desktop, unless overridden will also be used for tablet and mobile.
  tablet:
    comments: Styles for Tablet, unless overridden will also be used for mobile.
  mobile:
    comments: Styles for mobile.
  border_color:
    type: select
    options:
      values:
        - bronze
        - silver
        - platinum
        - gold

_structure:
  benefits:
    values:
      - value:
          text:
          tooltip:
          bold:
