# Metadata about this component, to be used in the CMS
spec:
  structures:
    - blocks
  label: "Logo Box"
  description: A container which can display logos around it
  icon: web_stories
  tags: ['containers']

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    blocks: []
    pizazz: []
  styles:
    desktop:
      margin:
        top: 0
        right: 0
        bottom: 0
        left: 0
      padding:
        top: 0
        right: 0
        bottom: 0
        left: 0
    tablet:
      margin:
        active: false
        top: 0
        right: 0
        bottom: 0
        left: 0
      padding:
        active: false
        top: 0
        right: 0
        bottom: 0
        left: 0
    mobile:
      margin:
        active: false
        top: 0
        right: 0
        bottom: 0
        left: 0
      padding:
        active: false
        top: 0
        right: 0
        bottom: 0
        left: 0

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  active:
    comment: These values won't be used unless active is enabled.
  desktop:
    comments: Styles for Desktop, unless overridden will also be used for tablet and mobile.
  tablet:
    comments: Styles for Tablet, unless overridden will also be used for mobile.
  mobile:
    comments: Styles for mobile.
  blocks:
    comments: Add components inside this section.
  pizazz:
    comments: Add logos inside this section
  margin:
    comment: Adjust the spacing between this container and others. Can be negative for overlapping.
  padding:
    comment: Adjust the spacing inside this container.
  top:
    type: number
  right:
    type: number
  bottom:
    type: number
  left:
    type: number
  