# Metadata about this component, to be used in the CMS
spec:
  structures:
    - blocks
  label: "Review-with-image"
  description:
  icon: vertical_split
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    title:
    reviews:
      - tab_name:
          text:
          image: 
            image_path:
            alt_text:
        quote:
          text_content:
          author:
          job_title:
        image:
          image_path:
          alt_text:
        button: bookshop:simple/button-holder
  styles:


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text_content:
    type: markdown 
