# Metadata about this component, to be used in the CMS
spec:
  structures:
    - blocks
  label: "Emoji heading"
  description: A special type of heading with a emoji, sub heading, and main heading
  icon: waving_hand
  tags: ['content']

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    title:
    emoji:
    sub_title: 
  styles:
    width:
    element: h3
    desktop:
      text_alignment:
        align: center
      margin:
        top: 0
        bottom: 0
    tablet:
      text_alignment:
        active: false
        align: center
      margin:
        active: false
        top: 0
        bottom: 0
    mobile:
      text_alignment:
        active: false
        align: center
      margin:
        active: false
        top: 0
        bottom: 0


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    comment: The main heading
  sub_title:
    comment: The sub heading
  emoji:
    comment: An optional emoji to display above the headings
  element:
    type: select
    comment: The type of heading.
    options:
      values:
        - h1
        - h2
        - h3
        - h4
        - h5
        - h6
  width:
    comment: The width of the text block
    type: select 
    options:
      values:
        - tight
        - full
  margin:
    comment: Adjust the spacing between the component and other components. Can be negative for overlapping.
  top:
    type: number
  bottom:
    type: number
  align:
    type: select
    comment: The alignment of the heading.
    options:
      values:
        - left
        - center
        - right
        - justify