# Metadata about this component, to be used in the CMS
spec:
  structures:
    - blocks
  label: "Small Card"
  description: "A small stand alone card"
  icon: clarify
  tags: ['content']

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    icon:
      hide_icon: false
      icon_path: outline/language
      icon_color: teal
    info_pill:
    blocks: []
  styles:
    border_color: 
    background:
    desktop:
      margin:
        top: 0
        bottom: 0
    tablet:
      margin:
        active: false
        top: 0
        bottom: 0
    mobile:
      margin:
        active: false
        top: 0
        bottom: 0

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  active:
    comment: These values won't be used unless active is enabled.
  desktop:
    comments: Styles for Desktop, unless overridden will also be used for tablet and mobile.
  tablet:
    comments: Styles for Tablet, unless overridden will also be used for mobile.
  mobile:
    comments: Styles for mobile.
  background:
    type: select
    comment: The background color for the entire section
    options:
      values:
        - white
        - caramel
        - sky
        - sea
        - cloudinary-blue
        - ash
        - night
        - midnight
  border_color:
    type: select
    options:
      values:
        - white
        - carbon
        - grey
        - cloudinary-blue
        - none
  icon_color:
    hidden: hide_icon 
  icon_path:
    hidden: hide_icon