# Metadata about this component, to be used in the CMS
spec:
  structures:
    - blocks
  label: "Video"
  description: Component that when clicked, opens a video in a modal.
  icon: tv
  tags: ['content']

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    placeholder_image: 
      desktop_image: 
      tablet_image: 
      mobile_image:
    video: "https://player.vimeo.com/video/668496650?h=88572f7829&amp;app_id=122963"
    title: "How does CloudCannon work?"
  styles:
    desktop:
      margin:
        top: 0
        right: 0
        bottom: 0
        left: 0
      position:
        top:
        left:
        bottom:
        right:
      transform:
        scale: 1
        translate_x: 0
        translate_y: 0
        rotate: 0
        skew: 0
    tablet:
      margin:
        active: false
        top: 0
        right: 0
        bottom: 0
        left: 0
      position:
        active: false
        top: 0
        left: 0
        bottom: 0
        right: 0
      transform:
        active: false
        scale: 1
        translate_x: 0
        translate_y: 0
        rotate: 0
        skew: 0
    mobile:
      margin:
        active: false
        top: 0
        right: 0
        bottom: 0
        left: 0
      position:
        active: false
        top: 0
        left: 0
        bottom: 0
        right: 0
      transform:
        active: false
        scale: 1
        translate_x: 0
        translate_y: 0
        rotate: 0
        skew: 0
    

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  active:
    comment: These values won't be used unless active is enabled.
    type: switch
  desktop:
    comments: Styles for Desktop, unless overridden will also be used for tablet and mobile.
  tablet:
    comments: Styles for Tablet, unless overridden will also be used for mobile.
  mobile:
    comments: Styles for mobile.
  placeholder_image:
    comment: 'The image that will show on the page. Clicking on it will open the video.'
  video:
    comment: The URL of the vimeo video
    type: url
  title:
    comment: For accessibility, doesn't actually show on the page.
  margin:
    comment: Adjust the spacing between this container and others. Can be negative for overlapping.
  transform:
    comment: Different methods to change how this component displays
  scale:
    comment: Increase or decrease the size of the image. 1.0 is the default scale
    type: number
  translate_x:
    comment: Shift the image horizontally
    type: number
  translate_y:
    comment: Shift the image vertically
    type: number
  rotate:
    comment: Rotate the image
    type: range
    options:
      step: 1
      max: 359
      min: 0
  skew:
    comment: Skew the image
    type: range
    options:
      step: 1
      max: 359
      min: 0