# Metadata about this component, to be used in the CMS
spec:
  structures:
    - logo_blocks
  label: "Logo"
  description: The logos inside a logo ticker
  icon: polymer
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    logo: /src/images/logos/netflix.svg
    name: Netflix
    url:
  styles:
    desktop:
      visibility:
        hide: false
      position:
        top: 0
        right: 0
        bottom: 0
        left: 0
      transform:
        scale: 1
        translate_x: 0
        translate_y: 0
        rotate: 0
        skew: 0
    tablet:
      visibility:
        active: false
        hide: true
      position:
        active: false
        top: 0
        right: 0
        bottom: 0
        left: 0
      transform:
        active: false
        scale: 1
        translate_x: 0
        translate_y: 0
        rotate: 0
        skew: 0
    mobile:
      visibility:
        active: false
        hide: true
      position:
        active: false
        top: 0
        right: 0
        bottom: 0
        left: 0
      transform:
        active: false
        scale: 1
        translate_x: 0
        translate_y: 0
        rotate: 0
        skew: 0
    extra_classes: ""
  
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  active:
    comment: These values won't be used unless active is enabled.
    type: switch
  desktop:
    comments: Styles for Desktop, unless overridden will also be used for tablet and mobile.
  tablet:
    comments: Styles for Tablet, unless overridden will also be used for mobile.
  mobile:
    comments: Styles for mobile.
  position:
    comment: Adjust the position of this logo.
  logo:
    type: image
    comment: The path to this logo
  name:
    comment: Used for accessibility, doesn't show on the page otherwise
  top:
    type: number
  right:
    type: number
  bottom:
    type: number
  left:
    type: number
  transform:
    comment: Different methods to change how this component displays
  scale:
    comment: Increase or decrease the size of the video. 1.0 is the default scale
    type: number
  translate_x:
    comment: Shift the video horizontally
    type: number
  translate_y:
    comment: Shift the video vertically
    type: number
  rotate:
    comment: Rotate the video
    type: range
    options:
      step: 1
      max: 359
      min: 0
  skew:
    comment: Skew the video
    type: range
    options:
      step: 1
      max: 359
      min: 0
  extra_classes:
    comment: Special circumstances. Allows you to add a class to a button (You probably don't need this).
