# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Markdown Youtube"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  id:
  title: 
  border: false
  extend: false
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
