site_url: https://cloudinary.com
site_name: Cloudinary
site_title: Cloudinary
favicon: "https://res.cloudinary.com/cloudinary-marketing/images/w_32,h_32,c_fill/f_auto,q_auto/v1645214625/website-2021/blog/favicon-og_1937735151/favicon-og_1937735151-png?_i=AA?w=32"
description: Streamline media management and improve user experience by automatically delivering images and videos, enhanced and optimized for every user.
twitter_site: "@cloudinary"
image: "https://res.cloudinary.com/cloudinary-marketing/image/upload/f_auto,q_auto/v1597642219/creative_source/Brand/Social%20Images/Cld_SocShare_Card_FB_2020.png"
image_alt: "Showcasing editor options"
