# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Button"
  description: A button you click on and it does something
  icon: smart_button
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: "I'm a button"
  link: "/"
  style: "normal"
  size: "normal"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    comment: The text for the button
  link:
    type: url
    comment: Where to go when the button is clicked
  style:
    comment: The color combination of the button
    type: select
    options:
      values:
        - normal
        - outline
        - outline-white
        - white
        - plain-text
  size:
    comment: The size of the button.
    type: select
    options:
      values:
        - normal
        - big
  extra_classes:
    comment: Special circumstances. Allows you to add a class to a button (You probably don't need this).
