# Metadata about this component, to be used in the CMS
spec:
  structures:
    - blocks
  label: "Expandable List"
  description: Click on a heading to expand more information
  icon: view_list
  tags: ['content']

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    rows:
      - title: What happens at the end of my trial?
        description: Before the end of your trial, we'll send you an email asking you to enter your credit card to continue using CloudCannon. If no credit card is entered by the end of the trial, you'll be downgraded to our personal plan.
        prefix_icon:
          icon_path:
          icon_color:
  styles:
    background: transparent-light
    gaps: false
    rotate: true
    size: big
    dropdown_icon:
      icon_path: solid/plus
      icon_color: midnight
    active_dropdown_icon:
      icon_path: solid/minus
      icon_color: midnight
    desktop:
      transform:
        scale: 1
        translate_x: 0
        translate_y: 0
        rotate: 0
        skew: 0
      block_alignment:
        align_block: left
      margin:
        top: 0
        left: 0
        bottom: 0
        right: 0
      position:
        top: 0
        left: 0
        bottom: 0
        right: 0
    tablet:
      transform:
        active: false
        scale: 1
        translate_x: 0
        translate_y: 0
        rotate: 0
        skew: 0
      block_alignment:
        active: false
        align_block: left
      margin:
        active: false
        top: 0
        left: 0
        bottom: 0
        right: 0
      position:
        active: false
        top: 0
        left: 0
        bottom: 0
        right: 0
    mobile:
      transform:
        active: false
        scale: 1
        translate_x: 0
        translate_y: 0
        rotate: 0
        skew: 0
      block_alignment:
        active: false
        align_block: left
      margin:
        active: false
        top: 0
        left: 0
        bottom: 0
        right: 0
      position:
        active: false
        top: 0
        left: 0
        bottom: 0
        right: 0

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  transform:
    comment: Different methods to change how this component displays
  scale:
    comment: Increase or decrease the size of the video. 1.0 is the default scale
    type: number
  translate_x:
    comment: Shift the video horizontally
    type: number
  translate_y:
    comment: Shift the video vertically
    type: number
  rotate:
    comment: Rotate the video
    type: range
    options:
      step: 1
      max: 359
      min: 0
  skew:
    comment: Skew the video
    type: range
    options:
      step: 1
      max: 359
      min: 0
  align_block:
    comment: Aligns the entire block
    options:
      values:
        - left
        - center
  size:
    comment: The size of the icon and heading
    options:
      values:
        - big
        - normal
  margin:
    comment: Adjust the spacing between this container and others. Can be negative for overlapping.
  top:
    type: number
  right:
    type: number
  bottom:
    type: number
  left:
    type: number
  description:
    type: markdown

_structures:
  rows:
    values: 
      - value:
          title:
          description:
          image: